### ISSUE TITLE
Error on send_wait_result on testnet only

### ISSUE THREAD

**Issue by Abdel-Mecheri** [ElrondNetwork/elrond-sdk-erdpy#110]
Hello,

I have an error on erpdy python cli when i send a transaction on testnet, the transaction is send with success, but there is a error in my console.

```
  File "/home/***/.local/lib/python3.10/site-packages/erdpy/transactions.py", line 125, in send_wait_result
    response = proxy.send_transaction_and_wait_for_result(self.to_dictionary(), timeout)
  File "/home/***/.local/lib/python3.10/site-packages/erdpy/proxy/core.py", line 149, in send_transaction_and_wait_for_result
    if self.is_transaction_finalized(tx_hash):
  File "/home/***/.local/lib/python3.10/site-packages/erdpy/proxy/core.py", line 157, in is_transaction_finalized
    finalized_transactions = last_hyperblock["transactions"]
KeyError: 'transactions'
```

This code work on devnet correctly.

My code : 

```
def sendTransaction(value, receiver, data, env):
    proxy = getProxy(env)
    sender.sync_nonce(proxy)
    tx = Transaction()
    tx.nonce = sender.nonce
    tx.value = str(int(value * 10**18))
    tx.sender = sender.address.bech32()
    tx.receiver = receiver
    tx.gasPrice = 1000000000
    tx.gasLimit = 60000000
    tx.data = data
    tx.chainID = proxy.get_chain_id()
    tx.version = 1
    tx.signature = sender.sign_transaction(tx)
    return tx.send_wait_result(proxy, 120)

response = sendTransaction(0.05, "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u", data, env)
print(response)
```
The data is good and the env too.

The transaction : https://testnet-explorer.elrond.com/transactions/16ea8e63632107fca3459bae68899d7c38d6cfdf40ab38906b85f3b6133ff82a

Did somebody have this problem or a solution ?

**Comment by andreibancioiu** [comment]
Hello @Abdel-Mecheri! It seems that you are using an older version of erdpy (by looking at the error).

Could you please install the latest version and try again? :pray: 

https://docs.elrond.com/sdk-and-tools/erdpy/installing-erdpy/#install-using-erdpy-up-recommended

Does the error persist?

**Comment by andreibancioiu** [comment]
Perhaps you can have a look in this PR, in the file `examples/contracts.py`, where you can see an example of `send_wait_result()`: https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/120

**Comment by Abdel-Mecheri** [comment]
Wy have wallet have been reset on the testnet, i have to wait 24h to get faucet and test it

**Comment by andreibancioiu** [comment]
The issue will be closed now. Please let us know otherwise :pray:
