### ISSUE TITLE
Transaction stuck in pending after sending with erdpy

### ISSUE THREAD

**Issue by mihaela1108** [ElrondNetwork/elrond-sdk-erdpy#116]
Hello,

I am trying to create transactions and I am using the documentation from here: https://docs.elrond.com/sdk-and-tools/erdpy/sending-bulk-transactions/?fbclid=IwAR2XspENj520peRP72kQsfDL-v-3W6lcRFw-lLbfvbHCcS5MezNeNc1dwFY. I created the pem file for my wallet and modified the transactions.sh accordingly, it looks as below:

`function send-bulk-tx {
  for transaction in "${TRANSACTIONS[@]}"; do
    set -- $transaction
    erdpy tx new --send --outfile="bon-mission-tx-$NONCE.json" --pem=$PEM_FILE --nonce=$NONCE --receiver=$1 --value="$2$DENOMINATION" --gas-limit=50000 --proxy=$PROXY --chain="1"
    echo "Transaction sent with nonce $NONCE and backed up to bon-mission-tx-$NONCE.json."
    (( NONCE++ ))
  done
}`

The script executed successfully and I received the transaction link from elrond explorer, but the transaction remained in pending for some minutes and then disappeared. 
Am I missing anything, why does the transaction not work? Thank you

**Comment by andreibancioiu** [comment]
Hello @mihaela1108!

Currently, we do not recommend mixing bash scripting and erdpy anymore - the docs will be updated soon. Instead, we recommend you to write a Python script when you need to send multiple transactions (or simply invoke erdpy in the command line if you only need to send one transaction).

The following PR adds a series of examples: https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/120

You might be interested into the file `examples/minting.py`.

**Comment by andreibancioiu** [comment]
This issue will be closed now - Python scripts are recommended :pray:
