### ISSUE TITLE
Ledger Option does not work on Mac M1

### ISSUE THREAD

**Issue by keyur555** [ElrondNetwork/elrond-sdk-erdpy#118]
Hello,

I am trying to use the --ledger Option with Erdpy but I always get this error:

```
CRITICAL:cli:Ledger error: check if device is plugged in, unlocked and on Elrond app
```

I have the Elrond app open on my unlocked Ledger.

Other developers reported this error too on Mac M1.

Can we fix this? It would be really important because otherwise we have to put our private keys on the computer.

Thank you

**Comment by razvanstatescu** [comment]
Same problem here. Still no update on this?

**Comment by ionvv** [comment]
FYI, this happens not only on M1 chips. I've tried also on 2015 mbp with Catalina and mac mini with Big Sur and it's throwing same error.

**Comment by keyur555** [comment]
It works now after the latest update
