### ISSUE TITLE
Prompt for password if passfile not specified

### ISSUE THREAD

**Issue by lcswillems** [ElrondNetwork/elrond-sdk-erdpy#66]
Hi,

Prompting for password when signing a transaction seems better than storing the password in clear in a file in one's hard drive. The main advantage is that the password vanishes once it is entered in the prompt and so no traces remain.

I would be happy to do a PR to add this feature. Would this be something that would be accepted?

Best,
Lucas

**Comment by andreibancioiu** [comment]
Hello @lcswillems!

Sure, you can create a PR with this feature. However, please keep the CLI parameter `--passfile` as well - even if you make it optional. The existing behavior is useful in various scripts and automated flows.

**Comment by lcswillems** [comment]
Hi @andreibancioiu 

I made a PR: https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/144
