### ISSUE TITLE
erdpy: command not found

### ISSUE THREAD

**Issue by bitconnector21** [ElrondNetwork/elrond-sdk-erdpy#91]
I'm getting `erdpy: command not found` after running `python3.8 erdpy-up.py`

**Comment by andreibancioiu** [comment]
Hi @bitconnector21! 

What operating system are you using? Did the output of `erdpy-up` contain any error message?

**Comment by andreibancioiu** [comment]
Upon installing [erdpy using erdpy-up](https://docs.elrond.com/sdk-and-tools/erdpy/installing-erdpy/#install-using-erdpy-up-recommended), make sure to follow the instructions depicted in the terminal:

```
INFO:installer:You have successfully installed erdpy.
INFO:installer:Checking PATH variable.
INFO:installer:elrond-sdk path (/home/andrei/elrondsdk) already in $PATH variable.
INFO:installer:
###############################################################################
Upon restarting the user session, [$ erdpy] command should be available in your shell.
Furthermore, after restarting the user session, you can use [$ source erdpy-activate] to activate the Python virtual environment containing erdpy.
###############################################################################
```

After restarting the user session, `erdpy` command should be available in your shell.
